
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swcubveqtvjhqwawgcks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3Y3VidmVxdHZqaHF3YXdnY2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzE4MDYsImV4cCI6MjA2NTY0NzgwNn0.KHkPNj7-685p_-LK-L_8JfO2mzvDrIDfgeiUlvOFBmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Set session to persist for 100 days
    storageKey: 'supabase.auth.token',
    // Configure session persistence duration
    flowType: 'pkce'
  }
});
